import { StyleSheet } from "react-native";
import Metrics from "../../../Assets/Constants/Metrics";

export default StyleSheet.create({
  container: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    marginTop: Metrics.measure(5),
    width: Metrics.measure(330),
    height: Metrics.measure(50),
    margin: Metrics.measure(12),
    padding: Metrics.measure(10),
    backgroundColor: "#b3175e",
    borderRadius: Metrics.measure(5),
    fontSize: Metrics.measure(12),
    color: "#FFF",
  },
  inputManual: {
    marginTop: Metrics.measure(35),
    width: Metrics.measure(280),
    height: Metrics.measure(50),
    margin: Metrics.measure(12),
    padding: Metrics.measure(10),
    borderColor: "#b3175e",
    borderRadius: Metrics.measure(5),
    fontSize: Metrics.measure(12),
    borderWidth: Metrics.measure(1),
    color: "#000",
  },
  qrIcon: {
    width: Metrics.measure(40),
    height: Metrics.measure(40),
    position: "absolute",
    right: Metrics.measure(25),
    top: Metrics.measure(10),
  },
  closeContainer: {
    position: "absolute",
    right: Metrics.measure(5),
    top: Metrics.measure(5),
  },
  close: {
    width: Metrics.measure(30),
    height: Metrics.measure(30),
    zIndex: 10000000,
  },
  qrContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: Metrics.measure(15),
  },
  submitContainerBtn: {
    width: Metrics.measure(130),
    height: Metrics.measure(50),
    borderRadius: Metrics.measure(5),
    marginTop: Metrics.measure(5),
    backgroundColor: "#b3175e",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Metrics.measure(15),
  },
  submitContainerBtnMan: {
    width: Metrics.measure(280),
    height: Metrics.measure(50),
    borderRadius: Metrics.measure(5),
    marginTop: Metrics.measure(5),
    backgroundColor: "#b3175e",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Metrics.measure(15),
    marginLeft: Metrics.measure(13),
  },
  submitText: {
    color: "#FFF",
    fontSize: Metrics.measure(14),
    fontWeight: "700",
  },
  absoluteFillObject: {
    marginTop: Metrics.measure(30),
    marginBottom: Metrics.measure(10),
    width: "95%",
    height: Metrics.measure(450),
    borderRadius: Metrics.measure(5),
  },
  flashIcon: {
    width: Metrics.measure(30),
    height: Metrics.measure(30),
  },
  submitContainerBtnFlash: {
    width: Metrics.measure(60),
    height: Metrics.measure(50),
    borderRadius: Metrics.measure(5),
    marginTop: Metrics.measure(5),
    backgroundColor: "#b3175e",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Metrics.measure(15),
  },
  qrTextApprove: {
    color: "#FFF",
    fontSize: Metrics.measure(12),
    marginLeft: Metrics.measure(7),
    marginTop: Metrics.measure(3),
  },
  submitContainerBtnApprove: {
    width: Metrics.measure(160),
    height: Metrics.measure(50),
    borderRadius: Metrics.measure(5),
    marginTop: Metrics.measure(5),
    backgroundColor: "#b3175e",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Metrics.measure(15),
    flexDirection: "row",
  },
  approveIcon: {
    width: Metrics.measure(20),
    height: Metrics.measure(20),
  },
});
